//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomeLibrary.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The App.
        /// </summary>
        public static string AboutTheApp {
            get {
                return ResourceManager.GetString("AboutTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi. I like reading book a lot. And after Awesome Note app, i decide to create an app which has similar properties like GoodReads. You can add categories, add authors and add books on it. You can send information of your books via SMS, E-Mail and Social Media share (like Facebook etc.). I hope that you will like this app. If you rate app and write your suggestions to marketplace and coderserdar@outlook.com I will be so appreciated to you. With my best regards. ÇMS Software..
        /// </summary>
        public static string AboutTheAppText {
            get {
                return ResourceManager.GetString("AboutTheAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The Awesome Library.
        /// </summary>
        public static string AboutTheAwesomeLibrary {
            get {
                return ResourceManager.GetString("AboutTheAwesomeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Author.
        /// </summary>
        public static string AddAuthor {
            get {
                return ResourceManager.GetString("AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        public static string AddBook {
            get {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Has Been Added Successfully.
        /// </summary>
        public static string AuthorAddSuccess {
            get {
                return ResourceManager.GetString("AuthorAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Has This Category Already.
        /// </summary>
        public static string AuthorAlreadySameCategory {
            get {
                return ResourceManager.GetString("AuthorAlreadySameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Has Been Added To Author Successfully.
        /// </summary>
        public static string AuthorCategoryAddSuccess {
            get {
                return ResourceManager.GetString("AuthorCategoryAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Has Been Removed Successfully.
        /// </summary>
        public static string AuthorDeleteSuccess {
            get {
                return ResourceManager.GetString("AuthorDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Author Has Already Exists.
        /// </summary>
        public static string AuthorExists {
            get {
                return ResourceManager.GetString("AuthorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author List.
        /// </summary>
        public static string AuthorList {
            get {
                return ResourceManager.GetString("AuthorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name Has Been Changed Successfully.
        /// </summary>
        public static string AuthorNameChangeSuccess {
            get {
                return ResourceManager.GetString("AuthorNameChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Order By.
        /// </summary>
        public static string AuthorOrderBy {
            get {
                return ResourceManager.GetString("AuthorOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Order Style.
        /// </summary>
        public static string AuthorOrderStyle {
            get {
                return ResourceManager.GetString("AuthorOrderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Order Style Has Been Changed Successfully.
        /// </summary>
        public static string AuthorOrderStyleChangeSuccess {
            get {
                return ResourceManager.GetString("AuthorOrderStyleChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Order Type Has Been Changed Successfully.
        /// </summary>
        public static string AuthorOrderTypeChangeSuccess {
            get {
                return ResourceManager.GetString("AuthorOrderTypeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Settings.
        /// </summary>
        public static string AuthorSettings {
            get {
                return ResourceManager.GetString("AuthorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color Has Been Changed Successfully.
        /// </summary>
        public static string BackgroundColorChangeSuccess {
            get {
                return ResourceManager.GetString("BackgroundColorChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Has Been Changed Successfully.
        /// </summary>
        public static string BackgroundImageChangeSuccess {
            get {
                return ResourceManager.GetString("BackgroundImageChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Has Been Removed Successfully.
        /// </summary>
        public static string BackgroundImageRemoveSuccess {
            get {
                return ResourceManager.GetString("BackgroundImageRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Book.
        /// </summary>
        public static string BestBook {
            get {
                return ResourceManager.GetString("BestBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Comment.
        /// </summary>
        public static string BookComment {
            get {
                return ResourceManager.GetString("BookComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Count.
        /// </summary>
        public static string BookCount {
            get {
                return ResourceManager.GetString("BookCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Has Been Removed Successfully.
        /// </summary>
        public static string BookDeleteSuccess {
            get {
                return ResourceManager.GetString("BookDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book List.
        /// </summary>
        public static string BookList {
            get {
                return ResourceManager.GetString("BookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        public static string BookName {
            get {
                return ResourceManager.GetString("BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have To Enter Book Name At Least.
        /// </summary>
        public static string BookNameMustBe {
            get {
                return ResourceManager.GetString("BookNameMustBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Order By.
        /// </summary>
        public static string BookOrderBy {
            get {
                return ResourceManager.GetString("BookOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Order Style.
        /// </summary>
        public static string BookOrderStyle {
            get {
                return ResourceManager.GetString("BookOrderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Order Style Has Been Changed Successfully.
        /// </summary>
        public static string BookOrderStyleChangeSuccess {
            get {
                return ResourceManager.GetString("BookOrderStyleChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Order Type Has Been Changed Successfully.
        /// </summary>
        public static string BookOrderTypeChangeSuccess {
            get {
                return ResourceManager.GetString("BookOrderTypeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Book Read Per Day.
        /// </summary>
        public static string BookPerDay {
            get {
                return ResourceManager.GetString("BookPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Rating.
        /// </summary>
        public static string BookRating {
            get {
                return ResourceManager.GetString("BookRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Has Been Saved Successfully.
        /// </summary>
        public static string BookSaveSuccess {
            get {
                return ResourceManager.GetString("BookSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Has Been Added Successfully.
        /// </summary>
        public static string CategoryAddSuccess {
            get {
                return ResourceManager.GetString("CategoryAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Has Been Removed Successfully.
        /// </summary>
        public static string CategoryDeleteSuccess {
            get {
                return ResourceManager.GetString("CategoryDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Category Has Already Exists.
        /// </summary>
        public static string CategoryExists {
            get {
                return ResourceManager.GetString("CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name Has Been Changed Successfully.
        /// </summary>
        public static string CategoryNameChangeSuccess {
            get {
                return ResourceManager.GetString("CategoryNameChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Order By.
        /// </summary>
        public static string CategoryOrderBy {
            get {
                return ResourceManager.GetString("CategoryOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Order Style.
        /// </summary>
        public static string CategoryOrderStyle {
            get {
                return ResourceManager.GetString("CategoryOrderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Order Style Has Been Changed Successfully.
        /// </summary>
        public static string CategoryOrderStyleChangeSuccess {
            get {
                return ResourceManager.GetString("CategoryOrderStyleChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Order Type Has Been Changed Successfully.
        /// </summary>
        public static string CategoryOrderTypeChangeSuccess {
            get {
                return ResourceManager.GetString("CategoryOrderTypeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Settings.
        /// </summary>
        public static string CategorySettings {
            get {
                return ResourceManager.GetString("CategorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact With Us.
        /// </summary>
        public static string ContactWithUs {
            get {
                return ResourceManager.GetString("ContactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Author.
        /// </summary>
        public static string DeleteAuthor {
            get {
                return ResourceManager.GetString("DeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Will Delete The Author With All Contents. Are You Sure?.
        /// </summary>
        public static string DeleteAuthorQuestion {
            get {
                return ResourceManager.GetString("DeleteAuthorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Book.
        /// </summary>
        public static string DeleteBook {
            get {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Will Delete This Book. Are You Sure?.
        /// </summary>
        public static string DeleteBookQuestion {
            get {
                return ResourceManager.GetString("DeleteBookQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Will Delete Category With All Contents. Do You Agree?.
        /// </summary>
        public static string DeleteCategoryQuestion {
            get {
                return ResourceManager.GetString("DeleteCategoryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Author Name.
        /// </summary>
        public static string EnterAuthorName {
            get {
                return ResourceManager.GetString("EnterAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Category Name.
        /// </summary>
        public static string EnterCategoryName {
            get {
                return ResourceManager.GetString("EnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit App.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Exit App?.
        /// </summary>
        public static string ExitAppQuestion {
            get {
                return ResourceManager.GetString("ExitAppQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family Has Been Changed Successfully.
        /// </summary>
        public static string FontFamilyChangeSuccess {
            get {
                return ResourceManager.GetString("FontFamilyChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size Has Been Changed Successfully.
        /// </summary>
        public static string FontSizeChangeSuccess {
            get {
                return ResourceManager.GetString("FontSizeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You May Restart Application To Change Affect.
        /// </summary>
        public static string LanguageWarning {
            get {
                return ResourceManager.GetString("LanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modification Date.
        /// </summary>
        public static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author You Most Read.
        /// </summary>
        public static string MostReadAuthor {
            get {
                return ResourceManager.GetString("MostReadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category You Most Read.
        /// </summary>
        public static string MostReadCategory {
            get {
                return ResourceManager.GetString("MostReadCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher You Most Read.
        /// </summary>
        public static string MostReadPublisher {
            get {
                return ResourceManager.GetString("MostReadPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        public static string OneDrive {
            get {
                return ResourceManager.GetString("OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive Sync Completed.
        /// </summary>
        public static string OneDriveSyncCompleted {
            get {
                return ResourceManager.GetString("OneDriveSyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number.
        /// </summary>
        public static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Page Read Per Day.
        /// </summary>
        public static string PagePerDay {
            get {
                return ResourceManager.GetString("PagePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Name.
        /// </summary>
        public static string PublisherName {
            get {
                return ResourceManager.GetString("PublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Background Image.
        /// </summary>
        public static string RemoveBackgroundImage {
            get {
                return ResourceManager.GetString("RemoveBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanskrit.
        /// </summary>
        public static string Sanskrit {
            get {
                return ResourceManager.GetString("Sanskrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Completed.
        /// </summary>
        public static string SearchCompleted {
            get {
                return ResourceManager.GetString("SearchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have To Fill Search Criteria.
        /// </summary>
        public static string SearchTrimFault {
            get {
                return ResourceManager.GetString("SearchTrimFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Background Color.
        /// </summary>
        public static string SelectBackgroundColor {
            get {
                return ResourceManager.GetString("SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Font Family.
        /// </summary>
        public static string SelectFontFamily {
            get {
                return ResourceManager.GetString("SelectFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Font Size.
        /// </summary>
        public static string SelectFontSize {
            get {
                return ResourceManager.GetString("SelectFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send With Awesome Library App.
        /// </summary>
        public static string SendWithApp {
            get {
                return ResourceManager.GetString("SendWithApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send With Mail.
        /// </summary>
        public static string SendWithMail {
            get {
                return ResourceManager.GetString("SendWithMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send With SMS.
        /// </summary>
        public static string SendWithSMS {
            get {
                return ResourceManager.GetString("SendWithSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Book.
        /// </summary>
        public static string ShareBook {
            get {
                return ResourceManager.GetString("ShareBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Settings Has Been Reset Successfully.
        /// </summary>
        public static string SuccessfulResetSettings {
            get {
                return ResourceManager.GetString("SuccessfulResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        public static string Synchronizing {
            get {
                return ResourceManager.GetString("Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync All In One File.
        /// </summary>
        public static string SyncOnOneFile {
            get {
                return ResourceManager.GetString("SyncOnOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Has A Fault. Please Try Again Later.
        /// </summary>
        public static string SystemFault {
            get {
                return ResourceManager.GetString("SystemFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Count You Read.
        /// </summary>
        public static string TotalBookCount {
            get {
                return ResourceManager.GetString("TotalBookCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst Book.
        /// </summary>
        public static string WorstBook {
            get {
                return ResourceManager.GetString("WorstBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
